---
- name: Configure host1
  hosts: host1
  tasks:
    - name: Create Port-Channel1 and enable it
      arista.eos.eos_interfaces:
        config:
          - name: Port-Channel1
            description: L3_Uplink_to_Core
            enabled: true
        state: merged

    - name: Add Ethernet1-2 into Po1 on host1
      arista.eos.eos_lag_interfaces:
        config:
          - name: Port-Channel1
            members:
              - member: Ethernet1
                mode: active
              - member: Ethernet2
                mode: active
        state: merged

    - name: Configure Po1 on host1
      arista.eos.eos_l3_interfaces:
        config:
          - name: Port-Channel1
            ipv4:
              - address: 10.1.10.11/24
        state: merged

    - name: Add static routes to host1
      arista.eos.eos_static_routes:
        config:
          - vrf: default
            address_families:
              - afi: ipv4
                routes:
                  - dest: 0.0.0.0/0
                    next_hops:
                      - forward_router_address: 10.1.10.1
        state: merged

- name: Configure host1
  hosts: host1, host2
  tasks:
    - name: Save config
      arista.eos.eos_command:
        commands:
          - "copy  running-config startup-config"
